In [106]:
import numpy as np
import pandas as pd

creating a dataframes

In [107]:
data={
    'Name':['anurag','sujal','pawan','aman'],
    'age':[10,20,30,40],
    'City':['mau','ghazipur','raipur','mardah'],
    'Salary':[65000,75000,85000,90000]
}
df=pd.DataFrame(data)

In [108]:
df

     Name  age      City  Salary
0  anurag   10       mau   65000
1   sujal   20  ghazipur   75000
2   pawan   30    raipur   85000
3    aman   40    mardah   90000

selactions and indxing of columns

In [109]:
df['Name']

0    anurag
1     sujal
2     pawan
3      aman
Name: Name, dtype: object

In [110]:
df[["City","Name"]]

       City    Name
0       mau  anurag
1  ghazipur   sujal
2    raipur   pawan
3    mardah    aman

creating a new columns

In [111]:
df["Designation"]=["dr.","eng.","lo.","dr."]
df

     Name  age      City  Salary Designation
0  anurag   10       mau   65000         dr.
1   sujal   20  ghazipur   75000        eng.
2   pawan   30    raipur   85000         lo.
3    aman   40    mardah   90000         dr.

remove a columns

In [112]:
df.drop("Designation",axis=1,inplace=True)

In [113]:
df

     Name  age      City  Salary
0  anurag   10       mau   65000
1   sujal   20  ghazipur   75000
2   pawan   30    raipur   85000
3    aman   40    mardah   90000

In [114]:
df.drop(["City","Salary"],axis=1)

     Name  age
0  anurag   10
1   sujal   20
2   pawan   30
3    aman   40

In [115]:
df

     Name  age      City  Salary
0  anurag   10       mau   65000
1   sujal   20  ghazipur   75000
2   pawan   30    raipur   85000
3    aman   40    mardah   90000

In [116]:
df.drop(0,axis=0)

    Name  age      City  Salary
1  sujal   20  ghazipur   75000
2  pawan   30    raipur   85000
3   aman   40    mardah   90000

In [117]:
 df.loc[0]

Name      anurag
age           10
City         mau
Salary     65000
Name: 0, dtype: object

selecting subaets of  rows and colomuns

In [118]:
df.loc[[0,1]][["City","Salary"]]

       City  Salary
0       mau   65000
1  ghazipur   75000

In [119]:
df.loc[[1,2]][["City","Salary"]]

       City  Salary
1  ghazipur   75000
2    raipur   85000

conditions

In [120]:
df

     Name  age      City  Salary
0  anurag   10       mau   65000
1   sujal   20  ghazipur   75000
2   pawan   30    raipur   85000
3    aman   40    mardah   90000

In [121]:
df[(df["age"]>=30) & (["City"]=="raipur")]

Empty DataFrame
Columns: [Name, age, City, Salary]
Index: []

missing data

In [122]:
import numpy as np
import pandas as pd

In [123]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df=pd.DataFrame(data)

In [124]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [125]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [126]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [127]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

In [128]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

removing missing data

In [129]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [130]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [131]:
df.dropna(thresh=4)

     A  B    C    D
0  1.0  1  1.0  1.0

In [ ]:
df.fillna(0)

TypeError: NDFrame.fillna() got an unexpected keyword argument 'thresh'

In [133]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [ ]:
Values ={}